/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const permissionGroups: any[] = [
    {
        "permissionName": "ohos.permission.LOCATION_IN_BACKGROUND",
        "groupName": "LOCATION",
        "label": $r("sys.string.ohos_lab_location_in_background"),
        "groupId": 0
    },
    {
        "permissionName": "ohos.permission.APPROXIMATELY_LOCATION",
        "groupName": "LOCATION",
        "label": $r("sys.string.ohos_lab_approximately_location"),
        "groupId": 0
    },
    {
        "permissionName": "ohos.permission.LOCATION",
        "groupName": "LOCATION",
        "label": $r("sys.string.ohos_lab_location"),
        "groupId": 0
    },
    {
        "permissionName": "ohos.permission.CAMERA",
        "groupName": "CAMERA",
        "label": $r("sys.string.ohos_lab_camera"),
        "groupId": 1
    },
    {
        "permissionName": "ohos.permission.MICROPHONE",
        "groupName": "MICROPHONE",
        "label": $r("sys.string.ohos_lab_microphone"),
        "groupId": 2
    },
    {
        "permissionName": "ohos.permission.ANSWER_CALL",
        "groupName": "PHONE",
        "label": $r("sys.string.ohos_lab_answer_call"),
        "groupId": 3
    },
    {
        "permissionName": "ohos.permission.MANAGE_VOICEMAIL",
        "groupName": "PHONE",
        "label": $r("sys.string.ohos_lab_manage_voicemail"),
        "groupId": 3
    },
    {
        "permissionName": "ohos.permission.READ_CELL_MESSAGES",
        "groupName": "SMS",
        "label": $r("sys.string.ohos_lab_read_cell_messages"),
        "groupId": 4
    },
    {
        "permissionName": "ohos.permission.READ_MESSAGES",
        "groupName": "SMS",
        "label": $r("sys.string.ohos_lab_read_messages"),
        "groupId": 4
    },
    {
        "permissionName": "ohos.permission.RECEIVE_MMS",
        "groupName": "SMS",
        "label": $r("sys.string.ohos_lab_receive_mms"),
        "groupId": 4
    },
    {
        "permissionName": "ohos.permission.RECEIVE_SMS",
        "groupName": "SMS",
        "label": $r("sys.string.ohos_lab_receive_sms"),
        "groupId": 4
    },
    {
        "permissionName": "ohos.permission.RECEIVE_WAP_MESSAGES",
        "groupName": "SMS",
        "label": $r("sys.string.ohos_lab_receive_wap_messages"),
        "groupId": 4
    },
    {
        "permissionName": "ohos.permission.SEND_MESSAGES",
        "groupName": "SMS",
        "label": $r("sys.string.ohos_lab_send_messages"),
        "groupId": 4
    },
    {
        "permissionName": "ohos.permission.READ_CONTACTS",
        "groupName": "CONTACTS",
        "label": $r("sys.string.ohos_lab_read_contacts"),
        "groupId": 5
    },
    {
        "permissionName": "ohos.permission.WRITE_CONTACTS",
        "groupName": "CONTACTS",
        "label": $r("sys.string.ohos_lab_write_contacts"),
        "groupId": 5
    },
    {
        "permissionName": "ohos.permission.READ_CALL_LOG",
        "groupName": "CALL_LOG",
        "label": $r("sys.string.ohos_lab_read_call_log"),
        "groupId": 6
    },
    {
        "permissionName": "ohos.permission.WRITE_CALL_LOG",
        "groupName": "CALL_LOG",
        "label": $r("sys.string.ohos_lab_write_call_log"),
        "groupId": 6
    },
    {
        "permissionName": "ohos.permission.MEDIA_LOCATION",
        "groupName": "MEDIA",
        "label": $r("sys.string.ohos_lab_media_location"),
        "groupId": 7
    },
    {
        "permissionName": "ohos.permission.READ_MEDIA",
        "groupName": "MEDIA",
        "label": $r("sys.string.ohos_lab_read_media"),
        "groupId": 7
    },
    {
        "permissionName": "ohos.permission.WRITE_MEDIA",
        "groupName": "MEDIA",
        "label": $r("sys.string.ohos_lab_write_media"),
        "groupId": 7
    },
    {
        "permissionName": "ohos.permission.READ_CALENDAR",
        "groupName": "CALENDAR",
        "label": $r("sys.string.ohos_lab_read_calendar"),
        "groupId": 8
    },
    {
        "permissionName": "ohos.permission.WRITE_CALENDAR",
        "groupName": "CALENDAR",
        "label": $r("sys.string.ohos_lab_write_calendar"),
        "groupId": 8
    },
    {
        "permissionName": "ohos.permission.ACTIVITY_MOTION",
        "groupName": "SPORT",
        "label": $r("sys.string.ohos_lab_activity_motion"),
        "groupId": 9
    },
    {
        "permissionName": "ohos.permission.READ_HEALTH_DATA",
        "groupName": "HEALTH",
        "label": $r("sys.string.ohos_lab_read_health_data"),
        "groupId": 10
    },
    {
        "permissionName": "ohos.permission.DISTRIBUTED_DATASYNC",
        "groupName": "OTHER",
        "icon": $r("app.media.ic_multi_device_vector"),
        "text": $r("app.string.group_label_distributed_datasync"),
        "label": $r("app.string.multi_device_collaboration"),
        "groupId": 11
    },
    {
        "permissionName": "ohos.permission.READ_IMAGEVIDEO",
        "groupName": "IMAGE_AND_VIDEOS",
        "label": $r('sys.string.ohos_desc_read_imagevideo'),
        "groupId": 12
    },
    {
        "permissionName": "ohos.permission.WRITE_IMAGEVIDEO",
        "groupName": "IMAGE_AND_VIDEOS",
        "label": $r('sys.string.ohos_desc_write_imagevideo'),
        "groupId": 12
    },
    {
        "permissionName": "ohos.permission.READ_AUDIO",
        "groupName": "AUDIOS",
        "label": $r('sys.string.ohos_desc_read_audio'),
        "groupId": 13
    },
    {
        "permissionName": "ohos.permission.WRITE_AUDIO",
        "groupName": "AUDIOS",
        "label": $r('sys.string.ohos_desc_write_audio'),
        "groupId": 13
    },
    {
        "permissionName": "ohos.permission.READ_DOCUMENT",
        "groupName": "DOCUMENTS",
        "label": $r('sys.string.ohos_desc_read_document'),
        "groupId": 14
    },
    {
        "permissionName": "ohos.permission.WRITE_DOCUMENT",
        "groupName": "DOCUMENTS",
        "label": $r('sys.string.ohos_desc_write_document'),
        "groupId": 14
    },
    {
        "permissionName": "ohos.permission.READ_WHOLE_CALENDAR",
        "groupName": "CALENDAR_ALL",
        "label": $r('sys.string.ohos_lab_read_whole_calendar'),
        "groupId": 15
    },
    {
        "permissionName": "ohos.permission.WRITE_WHOLE_CALENDAR",
        "groupName": "CALENDAR_ALL",
        "label": $r('sys.string.ohos_lab_write_whole_calendar'),
        "groupId": 15
    },
    {
        "permissionName": "ohos.permission.APP_TRACKING_CONSENT",
        "groupName": "ADS",
        "label": $r('sys.string.ohos_lab_app_tracking_consent'),
        "groupId": 16
    }
]

export const groups: any[] = [
    {
        "name": "LOCATION",
        "groupName": $r("app.string.groupName_location"),
        "icon": $r('app.media.ic_public_gps'),
        "description": "",
        "label": $r("app.string.group_label_location"),
        "permissions": [
            "ohos.permission.LOCATION_IN_BACKGROUND",
            "ohos.permission.APPROXIMATELY_LOCATION",
            "ohos.permission.LOCATION"
        ],
        "isShow":true
    },
    {
        "name": "CAMERA",
        "groupName": $r("app.string.groupName_camera"),
        "icon": $r('app.media.ic_public_camera'),
        "label": $r("app.string.group_label_camera"),
        "description": "",
        "permissions": [
            "ohos.permission.CAMERA"
        ],
        "isShow":true
    },
    {
        "name": "MICROPHONE",
        "groupName": $r("app.string.groupName_microphone"),
        "icon": $r('app.media.ic_public_voice'),
        "label": $r("app.string.group_label_microphone"),
        "description": "",
        "permissions": [
            "ohos.permission.MICROPHONE"
        ],
        "isShow":true
    },
    {
        "name": "PHONE",
        "groupName": $r("app.string.groupName_phone"),
        "icon": $r('app.media.ic_public_phone'),
        "label": $r("app.string.group_label_phone"),
        "description": "",
        "permissions": [
            "ohos.permission.ANSWER_CALL",
            "ohos.permission.MANAGE_VOICEMAIL"
        ],
        "isShow":false
    },
    {
        "name": "SMS",
        "groupName": $r("app.string.groupName_sms"),
        "icon": $r('app.media.ic_public_message'),
        "label": $r("app.string.group_label_sms"),
        "description": "",
        "permissions": [
            "ohos.permission.READ_CELL_MESSAGES",
            "ohos.permission.READ_MESSAGES",
            "ohos.permission.RECEIVE_MMS",
            "ohos.permission.RECEIVE_SMS",
            "ohos.permission.RECEIVE_WAP_MESSAGES",
            "ohos.permission.SEND_MESSAGES"
        ],
        "isShow":false
    },
    {
        "name": "CONTACTS",
        "groupName": $r("app.string.groupName_contacts"),
        "icon": $r('app.media.ic_public_contacts_group'),
        "label": $r("app.string.group_label_contacts"),
        "description": "",
        "permissions": [
            "ohos.permission.READ_CONTACTS",
            "ohos.permission.WRITE_CONTACTS"
        ],
        "isShow":false
    },
    {
        "name": "CALL_LOG",
        "groupName": $r("app.string.groupName_call_log"),
        "icon": $r('app.media.ic_call_logs'),
        "label": $r("app.string.group_label_call_log"),
        "description": "",
        "permissions": [
            "ohos.permission.READ_CALL_LOG",
            "ohos.permission.WRITE_CALL_LOG"
        ],
        "isShow":false
    },
    {
        "name": "MEDIA",
        "groupName": $r("app.string.groupName_media"),
        "icon": $r('app.media.ic_public_folder'),
        "description": "",
        "label": $r("app.string.group_label_media"),
        "permissions": [
            "ohos.permission.MEDIA_LOCATION",
            "ohos.permission.READ_MEDIA",
            "ohos.permission.WRITE_MEDIA"
        ],
        "isShow":true
    },
    {
        "name": "CALENDAR",
        "groupName": $r("app.string.groupName_calendar"),
        "icon": $r('app.media.ic_public_calendar'),
        "label": $r("app.string.group_label_calendar"),
        "description": "",
        "permissions": [
            "ohos.permission.READ_CALENDAR",
            "ohos.permission.WRITE_CALENDAR"
        ],
        "isShow":true
    },
    {
        "name": "SPORT",
        "groupName": $r("app.string.groupName_sport"),
        "icon": $r('app.media.ic_sport'),
        "label": $r("app.string.group_label_sport"),
        "description": "",
        "permissions": [
            "ohos.permission.ACTIVITY_MOTION"
        ],
        "isShow":true
    },
    {
        "name": "HEALTH",
        "groupName": $r("app.string.groupName_health"),
        "icon": $r('app.media.ic_ssensor'),
        "label": $r("app.string.group_label_health"),
        "description": "",
        "permissions": [
            "ohos.permission.READ_HEALTH_DATA"
        ],
        "isShow":true
    },
    {
        "name": "OTHER",
        "groupName": $r("app.string.groupName_other"),
        "icon": $r('app.media.ic_more'),
        "description": "",
        "permissions": [
            "ohos.permission.DISTRIBUTED_DATASYNC"
        ],
        "isShow":false
    },
    {
        "name": "IMAGE_AND_VIDEOS",
        "groupName": $r('sys.string.ohos_lab_read_imagevideo'),
        "icon": $r('app.media.ic_public_folder'),
        "label": $r("app.string.group_label_image_and_videos"),
        "description": "",
        "permissions": [
            "ohos.permission.READ_IMAGEVIDEO",
            "ohos.permission.WRITE_IMAGEVIDEO"
        ],
        "isShow":false
    },
    {
        "name": "AUDIOS",
        "groupName": $r('sys.string.ohos_lab_read_audio'),
        "icon": $r('app.media.ic_public_folder'),
        "label": $r("app.string.group_label_audios"),
        "description": "",
        "permissions": [
            "ohos.permission.READ_AUDIO",
            "ohos.permission.WRITE_AUDIO"
        ],
        "isShow":false
    },
    {
        "name": "DOCUMENTS",
        "groupName": $r('sys.string.ohos_lab_read_document'),
        "icon": $r('app.media.ic_public_folder'),
        "label": $r("app.string.group_label_document"),
        "description": "",
        "permissions": [
            "ohos.permission.READ_DOCUMENT",
            "ohos.permission.WRITE_DOCUMENT"
        ],
        "isShow":false
    },
    {
        "name": "CALENDAR_ALL",
        "groupName": $r("app.string.groupName_calendar_all"),
        "icon": $r('app.media.ic_public_calendar'),
        "label": $r("app.string.group_label_calendar_all"),
        "description": "",
        "permissions": [
            "ohos.permission.READ_WHOLE_CALENDAR",
            "ohos.permission.WRITE_WHOLE_CALENDAR"
        ],
        "isShow":false
    },
    {
        "name": "ADS",
        "groupName": $r("app.string.groupName_ADS"),
        "icon": $r('app.media.track'),
        "label": $r("app.string.group_label_ADS"),
        "description": "",
        "permissions": [
            "ohos.permission.APP_TRACKING_CONSENT"
        ],
        "isShow":false
    }
];

export const permissionGroupPermissions: object = {
    "LOCATION": [
        "ohos.permission.LOCATION_IN_BACKGROUND",
        "ohos.permission.APPROXIMATELY_LOCATION",
        "ohos.permission.LOCATION"
    ],
    "CAMERA": [
        "ohos.permission.CAMERA"
    ],
    "MICROPHONE": [
        "ohos.permission.MICROPHONE"
    ],
    "PHONE": [
        "ohos.permission.ANSWER_CALL",
        "ohos.permission.MANAGE_VOICEMAIL"
    ],
    "SMS": [
        "ohos.permission.READ_CELL_MESSAGES",
        "ohos.permission.READ_MESSAGES",
        "ohos.permission.RECEIVE_MMS",
        "ohos.permission.RECEIVE_SMS",
        "ohos.permission.RECEIVE_WAP_MESSAGES",
        "ohos.permission.SEND_MESSAGES"
    ],
    "CONTACTS": [
        "ohos.permission.READ_CONTACTS",
        "ohos.permission.WRITE_CONTACTS"
    ],
    "CALL_LOG": [
        "ohos.permission.READ_CALL_LOG",
        "ohos.permission.WRITE_CALL_LOG"
    ],
    "MEDIA": [
        "ohos.permission.MEDIA_LOCATION",
        "ohos.permission.READ_MEDIA",
        "ohos.permission.WRITE_MEDIA"
    ],
    "CALENDAR": [
        "ohos.permission.READ_CALENDAR",
        "ohos.permission.WRITE_CALENDAR"
    ],
    "SPORT": [
        "ohos.permission.ACTIVITY_MOTION"
    ],
    "HEALTH": [
        "ohos.permission.READ_HEALTH_DATA"
    ],
    "OTHER": [
        "ohos.permission.DISTRIBUTED_DATASYNC"
    ],
    "IMAGE_AND_VIDEOS": [
        "ohos.permission.READ_IMAGEVIDEO",
        "ohos.permission.WRITE_IMAGEVIDEO"
    ],
    "AUDIOS": [
        "ohos.permission.READ_AUDIO",
        "ohos.permission.WRITE_AUDIO"
    ],
    "DOCUMENTS": [
        "ohos.permission.READ_DOCUMENT",
        "ohos.permission.WRITE_DOCUMENT"
    ],
    "CALENDAR_ALL": [
        "ohos.permission.READ_WHOLE_CALENDAR",
        "ohos.permission.WRITE_WHOLE_CALENDAR"
    ],
    "ADS": [
        "ohos.permission.APP_TRACKING_CONSENT"
    ]
};


export const userGrantPermissions: string[] = [
    "ohos.permission.LOCATION_IN_BACKGROUND",
    "ohos.permission.APPROXIMATELY_LOCATION",
    "ohos.permission.LOCATION",
    "ohos.permission.CAMERA",
    "ohos.permission.MICROPHONE",
    "ohos.permission.ANSWER_CALL",
    "ohos.permission.MANAGE_VOICEMAIL",
    "ohos.permission.READ_CELL_MESSAGES",
    "ohos.permission.READ_MESSAGES",
    "ohos.permission.RECEIVE_MMS",
    "ohos.permission.RECEIVE_SMS",
    "ohos.permission.RECEIVE_WAP_MESSAGES",
    "ohos.permission.SEND_MESSAGES",
    "ohos.permission.READ_CONTACTS",
    "ohos.permission.WRITE_CONTACTS",
    "ohos.permission.READ_CALL_LOG",
    "ohos.permission.WRITE_CALL_LOG",
    "ohos.permission.MEDIA_LOCATION",
    "ohos.permission.READ_MEDIA",
    "ohos.permission.WRITE_MEDIA",
    "ohos.permission.READ_CALENDAR",
    "ohos.permission.WRITE_CALENDAR",
    "ohos.permission.ACTIVITY_MOTION",
    "ohos.permission.READ_HEALTH_DATA",
    "ohos.permission.DISTRIBUTED_DATASYNC",
    "ohos.permission.READ_IMAGEVIDEO",
    "ohos.permission.WRITE_IMAGEVIDEO",
    "ohos.permission.READ_AUDIO",
    "ohos.permission.WRITE_AUDIO",
    "ohos.permission.READ_DOCUMENT",
    "ohos.permission.WRITE_DOCUMENT",
    "ohos.permission.READ_WHOLE_CALENDAR",
    "ohos.permission.WRITE_WHOLE_CALENDAR",
    "ohos.permission.APP_TRACKING_CONSENT"
];

export const permissionGroupIds: object = {
    "ohos.permission.LOCATION_IN_BACKGROUND": "0",
    "ohos.permission.APPROXIMATELY_LOCATION": "0",
    "ohos.permission.LOCATION": "0",
    "ohos.permission.CAMERA": "1",
    "ohos.permission.MICROPHONE": "2",
    "ohos.permission.ANSWER_CALL": "3",
    "ohos.permission.MANAGE_VOICEMAIL": "3",
    "ohos.permission.READ_CELL_MESSAGES": "4",
    "ohos.permission.READ_MESSAGES": "4",
    "ohos.permission.RECEIVE_MMS": "4",
    "ohos.permission.RECEIVE_SMS": "4",
    "ohos.permission.RECEIVE_WAP_MESSAGES": "4",
    "ohos.permission.SEND_MESSAGES": "4",
    "ohos.permission.READ_CONTACTS": "5",
    "ohos.permission.WRITE_CONTACTS": "5",
    "ohos.permission.READ_CALL_LOG": "6",
    "ohos.permission.WRITE_CALL_LOG": "6",
    "ohos.permission.MEDIA_LOCATION": "7",
    "ohos.permission.READ_MEDIA": "7",
    "ohos.permission.WRITE_MEDIA": "7",
    "ohos.permission.READ_CALENDAR": "8",
    "ohos.permission.WRITE_CALENDAR": "8",
    "ohos.permission.ACTIVITY_MOTION": "9",
    "ohos.permission.READ_HEALTH_DATA": "10",
    "ohos.permission.DISTRIBUTED_DATASYNC": "11",
    "ohos.permission.READ_IMAGEVIDEO": "12",
    "ohos.permission.WRITE_IMAGEVIDEO": "12",
    "ohos.permission.READ_AUDIO": "13",
    "ohos.permission.WRITE_AUDIO": "13",
    "ohos.permission.READ_DOCUMENT": "14",
    "ohos.permission.WRITE_DOCUMENT": "14",
    "ohos.permission.READ_WHOLE_CALENDAR": "15",
    "ohos.permission.WRITE_WHOLE_CALENDAR": "15",
    "ohos.permission.APP_TRACKING_CONSENT": "16"
};

export const noNeedDisplayApp: string[] = [
    "com.ohos.launcher"
]

export const showSubpermissionsGrop: string[] = [
    "CALENDAR",
    "SMS",
    "CONTACTS",
    "CALL_LOG"
];

export const polymorphismGroup: string[] = [
    "LOCATION"
]

export const globalGroup: string[] = [
    "MICROPHONE",
    "CAMERA"
]