/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export default {
  "strings": {
    "mobileData": $r('app.string.mobile_data'),
    "general": $r('app.string.mobile_data_general'),
    "dataUsageFeesMayApply": $r('app.string.mobile_data_charges'),
    "dataRoaming": $r('app.string.mobile_data_dataRoaming'),
    "enableDataWhileRoaming": $r('app.string.mobile_data_enableDataWhileRoaming'),
    "notice": $r('app.string.mobile_data_tips'),
    "dataRoamingAsk": $r('app.string.mobile_data_turn_on_data_roaming'),
    "cancel": $r('app.string.cancel_space'),
    "confirm":$r('app.string.confim_space'),
    "netFive": $r('app.string.mobile_data_netFive'),
    "voCall": $r('app.string.mobile_data_volte'),
    "accessPointNamesAPN": $r('app.string.mobile_data_accessPointNamesAPN'),
    "sim1": $r('app.string.mobile_data_card1'),
    "sim2": $r('app.string.mobile_data_card2'),
    "preferredNetworkMode": $r('app.string.mobile_data_networkMode'),
    "networkProvider": $r('app.string.mobile_data_networkProvider'),
    "fiveAuto": $r('app.string.mobile_data_fiveAuto'),
    "fourAuto": $r('app.string.mobile_data_fourAuto'),
    "threeAuto": $r('app.string.mobile_data_threeAuto'),
    "twoOnly": $r('app.string.mobile_data_twoOnly'),
  }
}