/*
 * Copyright (c) 2022-2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { describe, beforeAll, beforeEach, afterEach, afterAll, it, expect } from '@ohos/hypium'
import { UiDriver, BY, UiComponent, MatchPattern } from '@ohos.uitest'
import AbilityDelegatorRegistry from '@ohos.application.abilityDelegatorRegistry'
import hilog from '@ohos.hilog'

const TAG = '[Sample_UtilTypeCheck]'
const DOMAIN = 0xF811
const BUNDLE = 'UtilTypeCheck_'

export default function appTest() {
  describe('appTest', function () {
    it(BUNDLE + 'StartAbilityFunction_001', 0, async function (done) {
      hilog.info(DOMAIN, TAG, BUNDLE + 'StartAbilityFunction_001 begin')
      let parameter = {
        bundleName: "ohos.samples.utiltypecheck",
        abilityName: "EntryAbility"
      }
      var abilityDelegator: any = AbilityDelegatorRegistry.getAbilityDelegator()
      await abilityDelegator.startAbility(parameter, (err, data) => {
        hilog.info(DOMAIN, TAG, BUNDLE + 'StartAbilityFunction_001,err.code:' + err.code)
        expect(0).assertEqual(err.code)
        done()
        hilog.info(DOMAIN, TAG, BUNDLE + 'StartAbilityFunction_001 end')
      })
    })
    /**
     * 点击显示预置值和校验预置值
     */
    it(BUNDLE + 'ClickDisplayAndCheckFunction_001', 0, async function () {
      hilog.info(DOMAIN, TAG, BUNDLE + 'ClickDisplayAndCheckFunction_001 begin')
      let driver = await UiDriver.create()
      await driver.delayMs(1000)
      hilog.info(DOMAIN, TAG, BUNDLE + 'ClickDisplayAndCheckFunction_001 clickDisplayPresetValue')
      // 点击显示预置值
      await driver.assertComponentExist(BY.key('displayPresetValue'))
      let displayPresetValueBtn = await driver.findComponent(BY.key('displayPresetValue'))
      await displayPresetValueBtn.click()
      await driver.delayMs(1000)
      hilog.info(DOMAIN, TAG, BUNDLE + 'ClickDisplayAndCheckFunction_001 clickCheckPresetValue')
      // 点击校验预置值
      await driver.assertComponentExist(BY.key('checkPresetValue'))
      let checkPresetValueBtn = await driver.findComponent(BY.key('checkPresetValue'))
      await checkPresetValueBtn.click()
      await driver.delayMs(1000)
      hilog.info(DOMAIN, TAG, BUNDLE + 'ClickDisplayAndCheckFunction_001 end')
    })
  })
}